### PR TITLE
simplify, remove duplication

### PR DESCRIPTION
**Pull request by dpolivaev**

### CODE REVIEW

**Comment by dpolivaev** [comment]
I am not sure how you like it.
My changes remove duplication in creating the title, but it needs to update the title when Freeplane is opened and it needs an extra method to find the map view. Nevertheless I understand my version better than yours.

Please let me know what you think.

**Comment by dpolivaev** [comment]
By the way, naming a branch like "test_edo" does not express the intent.

**Comment by dpolivaev** [comment]
If you like my changes you can merge them into your branch by accepting my pull request on your branch.

**Comment by EdoFro** [comment]
Hi Dimitry,
I just realized that you created these pull request. I will look at them and tell you my opinion.

> My changes remove duplication in creating the title, but it needs to update the title when Freeplane is opened and it needs an extra method to find the map view. Nevertheless I understand my version better than yours.

I will use your version. It is surely better than mine and I can learn from it.


Give me a few days to have a look at the changes.

**Pull request merged**
